#!/usr/bin/env bash
python -m ipdb -c continue main_maml.py \
    --env-name Point2DWalls-corner-v0 \
    --rewarder unsupervised \
    --clusterer vae \
    --cumulative-reward \
    --reward s_given_z \
    --conditional-coef 1 \
    --rewarder-fit-period 2 \
    --save-period 2 \
    --val-period 10 \
    --vis-period 2 \
    --subsample-num 1024 \
    --subsample-strategy last-random \
    --vae-beta 0.5 \
    --vae-lr 5e-4 \
    --vae-hidden-size 256 \
    --vae-latent-size 8 \
    --vae-layers 5 \
    --vae-plot \
    --vae-normalize \
    --vae-max-fit-epoch 2000 \
    --vae-batches 1 \
    --vae-marginal-samples 16 \
    --num-processes 20 \
    --episode-length 50 \
    --fast-lr 0.1 \
    --fast-batch-size 20 \
    --fast-lr-val-after-one 0.05 \
    --fast-batch-size-val 20 \
    --num-adapt-val 5 \
    --num-layers 2 \
    --hidden-size 256 \
    --bias-transformation-size 4 \
    --num-batches 100 \
    --meta-batch-size 40 \
    --gamma 0.99 \
    --tau 1.0 \
    --entropy-coef 0.001 \
    --entropy-coef-val 0.001 \
    --cg-damping 1e-5 \
    --max-kl 0.01 \
    --ls-max-steps 15 \
    --device cuda:0 \
    --seed 1 \
    --dense-coef 1 \
    --success-coef 10 \
    --log-dir-root ./output/debug/point2d/maml_vae